# Generated by Django 2.1.5 on 2019-08-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=500)),
                ('Passage', models.TextField()),
                ('Link', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
