# Generated by Django 2.1.5 on 2019-08-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CamCon', '0002_notices_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
