# Generated by Django 2.1.5 on 2019-08-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CamCon', '0004_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='comment',
            field=models.TextField(default='Tempo', max_length=500),
            preserve_default=False,
        ),
    ]
