# Generated by Django 2.1.5 on 2019-08-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CamCon', '0005_replies_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
